name: macOS trojan-gfw auto build

on:
  push:
    branches: [ main ]
    paths:
      - '**.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build-on-darwin:
    name: Build on Darwin
    runs-on: macos-latest
    steps:

    - name: Setup build environment
      run: |
        set -eufx
        #echo $0
        #whoami
        #sysctl -n machdep.cpu.brand_string
        #sysctl -n hw.ncpu
        #sw_vers
        #uname -a
        #xcode-select -p
        #xcodebuild -version
        #brew -v

        command -v cmake make > /dev/null

        brew install tree

        # Hack macOS 10.x to allow arm64* build support
        if [ "$(sw_vers -productVersion | cut -d'.' -f1)" = 10 ]; then
          pushd /Library/Developer/CommandLineTools/SDKs
          sudo rm MacOSX.sdk
          sudo ln -s MacOSX11.1.sdk MacOSX.sdk
          sudo rm -rf MacOSX10.15.sdk
          ls -l
          popd
        fi

        mkdir /tmp/trojan-darwin-universal

        pushd /tmp/trojan-darwin-universal
        curl -4sL https://formulae.brew.sh/api/formula/openssl@1.1.json | python3 -m json.tool | grep '"url":' | grep 'big_sur\.' | cut -d'"' -f4 | sort -V | tail -2 | xargs wget -q
        mkdir openssl_x86_64 openssl_arm64
        set +f
        ls -1 openssl*.tar.gz | grep arm64 | xargs -I{} tar xf '{}' -C openssl_arm64
        ls -1 openssl*.tar.gz | grep -v arm64 | xargs -I{} tar xf '{}' -C openssl_x86_64

        set -f
        curl -4sL https://formulae.brew.sh/api/formula/boost.json | python3 -m json.tool | grep '"url":' | grep 'big_sur\.' | cut -d'"' -f4 | sort -V | tail -2 | xargs wget -q
        mkdir boost_x86_64 boost_arm64

        set +f
        ls -1 boost*.tar.gz | grep arm64 | xargs -I{} tar xf '{}' -C boost_arm64
        ls -1 boost*.tar.gz | grep -v arm64 | xargs -I{} tar xf '{}' -C boost_x86_64
        set -f

        tree -L 4

        VER=$(curl -sL --retry 3 https://api.github.com/repos/trojan-gfw/trojan/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
        wget -q https://github.com/trojan-gfw/trojan/archive/$VER.tar.gz
        tar xf $VER.tar.gz
        pushd trojan-$(echo $VER | tr -d 'v')
        set +f
        OPENSSL_ROOT_DIR=$(realpath "$(ls -1d $PWD/../openssl_x86_64/*/*)")
        BOOST_INCLUDE_DIR=$(realpath "$(ls -1d $PWD/../boost_x86_64/*/*/include)")
        set -f
        cmake -DENABLE_MYSQL=OFF -DSYSTEMD_SERVICE=OFF -DBoost_USE_STATIC_LIBS=ON -DOPENSSL_USE_STATIC_LIBS=ON -DOPENSSL_ROOT_DIR=$OPENSSL_ROOT_DIR -DBoost_INCLUDE_DIR=$BOOST_INCLUDE_DIR -DDEFAULT_CONFIG=config.json .
        popd

        popd


