name: macOS trojan-gfw auto build

on:
  push:
    branches: [ main ]
    paths:
      - '**.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build-on-darwin:
    name: Build on Darwin
    runs-on: macos-latest
    steps:

    - name: Setup build environment
      run: |
        set -eufx
        echo $0
        whoami
        sysctl -n machdep.cpu.brand_string
        sysctl -n hw.ncpu
        sw_vers
        uname -a
        xcode-select -p
        xcodebuild -version
        brew -v
        curl -4sL https://icanhazip.com
        ifconfig

        # Hack macOS 10.x to allow arm64* build support
        if [ "$(sw_vers -productVersion | cut -d'.' -f1)" = 10 ]; then
          pushd /Library/Developer/CommandLineTools/SDKs
          sudo rm MacOSX.sdk
          sudo ln -s MacOSX11.1.sdk MacOSX.sdk
          sudo rm -rf MacOSX10.15.sdk
          ls -l
          popd
        fi

        brew install cmake
        mkdir /tmp/trojan-darwin-universal
        pushd /tmp/trojan-darwin-universal
        curl -4sL https://formulae.brew.sh/api/formula/openssl@1.1.json | python3 -m json.tool | grep '"url":' | grep 'big_sur\.' | cut -d'"' -f4 | sort -V | tail -2 | xargs wget
        curl -4sL https://formulae.brew.sh/api/formula/boost.json | python3 -m json.tool | grep '"url":' | grep 'big_sur\.' | cut -d'"' -f4 | sort -V | tail -2 | xargs wget
        popd

        pushd /tmp
        echo I2luY2x1ZGUgPHN0ZGlvLmg+CmludCBtYWluKHZvaWQpIHsKICAgIHB1dHMoIkhlbGxvIHdvcmxkISIpOwogICAgcmV0dXJuIDA7Cn0K | base64 -d > hello.c
        gcc -Wall -Wextra -arch x86_64 -arch arm64e hello.c -o hello
        lipo hello -verify_arch x86_64 arm64e
        file -b hello
        ./hello
        popd

