name: macOS trojan-gfw auto build

on:
  push:
    branches: [ main ]
    paths:
      - '**.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build-on-darwin:
    name: Build on Darwin
    runs-on: macos-latest
    steps:

    - name: Setup build environment
      run: |
        set -eufx
        sysctl -n machdep.cpu.brand_string
        sysctl -n hw.ncpu
        sw_vers
        uname -a
        xcode-select -p
        xcodebuild -version
        env

