name: macOS trojan-gfw auto build

on:
  push:
    branches: [ main ]
    paths:
      - '**.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build-on-darwin:
    name: Build on Darwin
    runs-on: macos-latest
    steps:

    - name: Setup build environment
      run: |
        set -eufx
        echo $0
        whoami
        sysctl -n machdep.cpu.brand_string
        sysctl -n hw.ncpu
        sw_vers
        uname -a
        xcode-select -p
        xcodebuild -version
        pushd /Library/Developer/CommandLineTools/SDKs
        sudo rm MacOSX.sdk
        sudo ln -s MacOSX11.1.sdk MacOSX.sdk
        popd
        pushd /tmp
        echo I2luY2x1ZGUgPHN0ZGlvLmg+CmludCBtYWluKHZvaWQpIHsKICAgIHB1dHMoIkhlbGxvIHdvcmxkISIpOwogICAgcmV0dXJuIDA7Cn0K | base64 -d > hello.c
        gcc -Wall -Wextra -arch x86_64 -arch arm64 hello.c -o hello
        file -b hello
        ./hello
        popd

